builds:
- id: kpm
  main: ./
  binary: kpm
  asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
  gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
  ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
  tags:
    - "{{ .Env.GO_BUILD_TAGS }}"
  mod_timestamp: "{{ .CommitTimestamp }}"
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - linux_s390x
  - linux_ppc64le

checksum:
  name_template: "checksums.txt"

archives:
- id: kpm
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
  strip_binary_directory: true
  format: binary

dockers:
  - image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-amd64"
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-arm64"
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
  - image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-ppc64le"
    goarch: ppc64le
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/ppc64le"
  - image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-s390x"
    goarch: s390x
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/s390x"

docker_manifests:
  - name_template: "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}"
    image_templates:
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-amd64"
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-arm64"
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-ppc64le"
      - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-s390x"

release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
