apiVersion: specs.kpm.io/v1
kind: Catalog

imageReference: quay.io/joelanford/kpm-demo-catalog:go-template-semver

migrationLevel: bundle-object-to-csv-metadata
cacheFormat: none

source:
  sourceType: fbcGoTemplate
  fbcGoTemplate:
    bundleSpecGlobs:
      - "../bundles/*.kpmspec.yaml"
    valuesFiles:
      - "semver-values.yaml"
    templateFile: "templates/semver.yaml.tmpl"
    templateHelperGlobs:
      - "templates/lib/*"

