description: An operator to manage argocd-operator in Kubernetes.
icon:
  base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMS44MiAzMiIgd2lkdGg9IjI0ODYiIGhlaWdodD0iMjUwMCI+PHRpdGxlPkNMPC90aXRsZT48cGF0aCBkPSJNMTkuNDIgOS4xN2ExNS4zOSAxNS4zOSAwIDAgMS0zLjUxLjQgMTUuNDYgMTUuNDYgMCAwIDEtMy41MS0uNCAxNS42MyAxNS42MyAwIDAgMSAzLjUxLTMuOTEgMTUuNzEgMTUuNzEgMCAwIDEgMy41MSAzLjkxek0zMCAuNTdBMTcuMjIgMTcuMjIgMCAwIDAgMjUuNTkgMGExNy40IDE3LjQgMCAwIDAtOS42OCAyLjkzQTE3LjM4IDE3LjM4IDAgMCAwIDYuMjMgMGExNy4yMiAxNy4yMiAwIDAgMC00LjQ0LjU3QTE2LjIyIDE2LjIyIDAgMCAwIDAgMS4xM2EuMDcuMDcgMCAwIDAgMCAuMDkgMTcuMzIgMTcuMzIgMCAwIDAgLjgzIDEuNTcuMDcuMDcgMCAwIDAgLjA4IDAgMTYuMzkgMTYuMzkgMCAwIDEgMS44MS0uNTQgMTUuNjUgMTUuNjUgMCAwIDEgMTEuNTkgMS44OCAxNy41MiAxNy41MiAwIDAgMC0zLjc4IDQuNDhjLS4yLjMyLS4zNy42NS0uNTUgMXMtLjIyLjQ1LS4zMy42OS0uMzEuNzItLjQ0IDEuMDhhMTcuNDYgMTcuNDYgMCAwIDAgNC4yOSAxOC43Yy4yNi4yNS41My40OS44MS43M3MuNDQuMzcuNjcuNTQuNTkuNDQuODkuNjRhLjA3LjA3IDAgMCAwIC4wOCAwYy4zLS4yMS42LS40Mi44OS0uNjRzLjQ1LS4zNS42Ny0uNTQuNTUtLjQ4LjgxLS43M2ExNy40NSAxNy40NSAwIDAgMCA1LjM4LTEyLjYxIDE3LjM5IDE3LjM5IDAgMCAwLTEuMDktNi4wOWMtLjE0LS4zNy0uMjktLjczLS40NS0xLjA5cy0uMjItLjQ3LS4zMy0uNjktLjM1LS42Ni0uNTUtMWExNy42MSAxNy42MSAwIDAgMC0zLjc4LTQuNDggMTUuNjUgMTUuNjUgMCAwIDEgMTEuNi0xLjg0IDE2LjEzIDE2LjEzIDAgMCAxIDEuODEuNTQuMDcuMDcgMCAwIDAgLjA4IDBxLjQ0LS43Ni44Mi0xLjU2YS4wNy4wNyAwIDAgMCAwLS4wOUExNi44OSAxNi44OSAwIDAgMCAzMCAuNTd6IiBmaWxsPSIjMTUxZjM0Ii8+PHBhdGggZD0iTTIxLjgyIDE3LjQ3YTE1LjUxIDE1LjUxIDAgMCAxLTQuMjUgMTAuNjkgMTUuNjYgMTUuNjYgMCAwIDEtLjcyLTQuNjggMTUuNSAxNS41IDAgMCAxIDQuMjUtMTAuNjkgMTUuNjIgMTUuNjIgMCAwIDEgLjcyIDQuNjgiIGZpbGw9IiMzNDg1NDAiLz48cGF0aCBkPSJNMTUgMjMuNDhhMTUuNTUgMTUuNTUgMCAwIDEtLjcyIDQuNjggMTUuNTQgMTUuNTQgMCAwIDEtMy41My0xNS4zN0ExNS41IDE1LjUgMCAwIDEgMTUgMjMuNDgiIGZpbGw9IiM3ZGJjNDIiLz48L3N2Zz4K
  mediatype: image/svg+xml

generateMajorChannels: true
generateMinorChannels: true
defaultChannelTypePreference: major

candidate:
  - argocd-operator.v0.0.2
  - argocd-operator.v0.0.3
  - argocd-operator.v0.0.4
  - argocd-operator.v0.0.5
  - argocd-operator.v0.0.6
  - argocd-operator.v0.0.8
  - argocd-operator.v0.0.9
  - argocd-operator.v0.0.11
  - argocd-operator.v0.0.12
  - argocd-operator.v0.0.13
  - argocd-operator.v0.0.14
  - argocd-operator.v0.0.15
  - argocd-operator.v0.1.0
  - argocd-operator.v0.2.0
  - argocd-operator.v0.2.1
  - argocd-operator.v0.3.0
  - argocd-operator.v0.4.0
  - argocd-operator.v0.5.0
  - argocd-operator.v0.6.0
  - argocd-operator.v0.7.0
  - argocd-operator.v0.8.0
  - argocd-operator.v0.9.0
  - argocd-operator.v0.9.1
  - argocd-operator.v0.9.2
  - argocd-operator.v0.10.0
  - argocd-operator.v0.10.1
  - argocd-operator.v0.11.0
  - argocd-operator.v1.10.0
  - argocd-operator.v1.10.1
fast:
  - argocd-operator.v0.1.0
  - argocd-operator.v0.2.0
  - argocd-operator.v0.2.1
  - argocd-operator.v0.3.0
  - argocd-operator.v0.4.0
  - argocd-operator.v0.5.0
  - argocd-operator.v0.6.0
  - argocd-operator.v0.7.0
  - argocd-operator.v0.8.0
  - argocd-operator.v0.9.0
  - argocd-operator.v0.9.1
  - argocd-operator.v0.9.2
  - argocd-operator.v0.10.0
  - argocd-operator.v0.10.1
  - argocd-operator.v0.11.0
  - argocd-operator.v1.10.0
  - argocd-operator.v1.10.1
stable:
  - argocd-operator.v0.11.0
  - argocd-operator.v1.10.0
  - argocd-operator.v1.10.1