apiVersion: specs.kpm.io/v1
kind: Catalog

imageReference: quay.io/joelanford/zookeeper-operator-catalog:latest

cacheFormat: none
migrationLevel: all

source:
  sourceType: legacy
  legacy:
    bundleRoot: .
    bundleImageReference: "quay.io/joelanford/{.PackageName}-bundle:v{.Version}"
