apiVersion: specs.kpm.io/v1
kind: Catalog

registryNamespace: quay.io/joelanford
name: zookeeper-operator-catalog
tag: latest

cacheFormat: none
migrationLevel: all

source:
  sourceType: legacy
  legacy:
    bundleRoot: .
    bundleRegistryNamespace: "quay.io/joelanford"
