apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: memcached-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.example.com
      resources:
      - kind: Deployment
        name: memcached-deployment
        version: v1
      specDescriptors:
      - description: Port defines the port that will be used to init the container
          with the image
        displayName: Container Port
        path: containerPort
      - description: Size defines the number of Memcached instances
        displayName: Size
        path: size
      statusDescriptors:
      - description: Conditions store the status conditions of the Memcached instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: Operator for managing memcached
  displayName: Memcached
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cache
  - memcached
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: joe.lanford@gmail.com
    name: Joe Lanford
  maturity: alpha
  provider:
    name: Joe Lanford
    url: https://memcached.org
  version: 0.0.0
