// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/experimental/api/graph/v1/entry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tags  map[string]*TagValues  `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Entry_Node
	//	*Entry_Edge
	Kind          isEntry_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_experimental_api_graph_v1_entry_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTags() map[string]*TagValues {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetKind() isEntry_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Entry) GetNode() *Node {
	if x != nil {
		if x, ok := x.Kind.(*Entry_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *Entry) GetEdge() *Edge {
	if x != nil {
		if x, ok := x.Kind.(*Entry_Edge); ok {
			return x.Edge
		}
	}
	return nil
}

type isEntry_Kind interface {
	isEntry_Kind()
}

type Entry_Node struct {
	Node *Node `protobuf:"bytes,2,opt,name=node,proto3,oneof"`
}

type Entry_Edge struct {
	Edge *Edge `protobuf:"bytes,3,opt,name=edge,proto3,oneof"`
}

func (*Entry_Node) isEntry_Kind() {}

func (*Entry_Edge) isEntry_Kind() {}

type TagValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagValues) Reset() {
	*x = TagValues{}
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagValues) ProtoMessage() {}

func (x *TagValues) ProtoReflect() protoreflect.Message {
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagValues.ProtoReflect.Descriptor instead.
func (*TagValues) Descriptor() ([]byte, []int) {
	return file_internal_experimental_api_graph_v1_entry_proto_rawDescGZIP(), []int{1}
}

func (x *TagValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Release       uint64                 `protobuf:"varint,3,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_internal_experimental_api_graph_v1_entry_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Node) GetRelease() uint64 {
	if x != nil {
		return x.Release
	}
	return 0
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Node                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *Node                  `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_experimental_api_graph_v1_entry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_internal_experimental_api_graph_v1_entry_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetFrom() *Node {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Edge) GetTo() *Node {
	if x != nil {
		return x.To
	}
	return nil
}

var File_internal_experimental_api_graph_v1_entry_proto protoreflect.FileDescriptor

const file_internal_experimental_api_graph_v1_entry_proto_rawDesc = "" +
	"\n" +
	".internal/experimental/api/graph/v1/entry.proto\x12\x02pb\"\xc0\x01\n" +
	"\x05Entry\x12'\n" +
	"\x04tags\x18\x01 \x03(\v2\x13.pb.Entry.TagsEntryR\x04tags\x12\x1e\n" +
	"\x04node\x18\x02 \x01(\v2\b.pb.NodeH\x00R\x04node\x12\x1e\n" +
	"\x04edge\x18\x03 \x01(\v2\b.pb.EdgeH\x00R\x04edge\x1aF\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.pb.TagValuesR\x05value:\x028\x01B\x06\n" +
	"\x04kind\"#\n" +
	"\tTagValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"N\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\arelease\x18\x03 \x01(\x04R\arelease\">\n" +
	"\x04Edge\x12\x1c\n" +
	"\x04from\x18\x01 \x01(\v2\b.pb.NodeR\x04from\x12\x18\n" +
	"\x02to\x18\x02 \x01(\v2\b.pb.NodeR\x02toB\x06Z\x04./pbb\x06proto3"

var (
	file_internal_experimental_api_graph_v1_entry_proto_rawDescOnce sync.Once
	file_internal_experimental_api_graph_v1_entry_proto_rawDescData []byte
)

func file_internal_experimental_api_graph_v1_entry_proto_rawDescGZIP() []byte {
	file_internal_experimental_api_graph_v1_entry_proto_rawDescOnce.Do(func() {
		file_internal_experimental_api_graph_v1_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_experimental_api_graph_v1_entry_proto_rawDesc), len(file_internal_experimental_api_graph_v1_entry_proto_rawDesc)))
	})
	return file_internal_experimental_api_graph_v1_entry_proto_rawDescData
}

var file_internal_experimental_api_graph_v1_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_experimental_api_graph_v1_entry_proto_goTypes = []any{
	(*Entry)(nil),     // 0: pb.Entry
	(*TagValues)(nil), // 1: pb.TagValues
	(*Node)(nil),      // 2: pb.Node
	(*Edge)(nil),      // 3: pb.Edge
	nil,               // 4: pb.Entry.TagsEntry
}
var file_internal_experimental_api_graph_v1_entry_proto_depIdxs = []int32{
	4, // 0: pb.Entry.tags:type_name -> pb.Entry.TagsEntry
	2, // 1: pb.Entry.node:type_name -> pb.Node
	3, // 2: pb.Entry.edge:type_name -> pb.Edge
	2, // 3: pb.Edge.from:type_name -> pb.Node
	2, // 4: pb.Edge.to:type_name -> pb.Node
	1, // 5: pb.Entry.TagsEntry.value:type_name -> pb.TagValues
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_experimental_api_graph_v1_entry_proto_init() }
func file_internal_experimental_api_graph_v1_entry_proto_init() {
	if File_internal_experimental_api_graph_v1_entry_proto != nil {
		return
	}
	file_internal_experimental_api_graph_v1_entry_proto_msgTypes[0].OneofWrappers = []any{
		(*Entry_Node)(nil),
		(*Entry_Edge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_experimental_api_graph_v1_entry_proto_rawDesc), len(file_internal_experimental_api_graph_v1_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_experimental_api_graph_v1_entry_proto_goTypes,
		DependencyIndexes: file_internal_experimental_api_graph_v1_entry_proto_depIdxs,
		MessageInfos:      file_internal_experimental_api_graph_v1_entry_proto_msgTypes,
	}.Build()
	File_internal_experimental_api_graph_v1_entry_proto = out.File
	file_internal_experimental_api_graph_v1_entry_proto_goTypes = nil
	file_internal_experimental_api_graph_v1_entry_proto_depIdxs = nil
}
